### ISSUE TITLE
[Feature request] API endpoints

### ISSUE THREAD

**Issue by nabbyte** [assetnote/wordlists#1]
Hey,
First of all thank you for this wonderful contribution to the infosec community.
Secondly, could you guys also create a wordlist consisting of API endpoints? For example:

/api/*
/v1/*
/v2/* 
etc

Thank you!

**Comment by infosec-au** [comment]
Hey @nabbyte 

You can find this wordlist at: https://s3.amazonaws.com/assetnote-wordlists/data/automated/httparchive_apiroutes_2020_11_20.txt

Thanks for the suggestion.

This wordlist will be generated on a monthly basis on top of everything else.
