### ISSUE TITLE
Are the lists ordered?

### ISSUE THREAD

**Issue by phnix-sec** [assetnote/wordlists#2]
Hi,

This is not an issue but a question regarding the order of the words inside each list. Are the words ordered in a specific way(like from most used to least used) or are they unordered.
Great project btw.

Thanks

**Comment by infosec-au** [comment]
Hey @phnix-sec - 

All the wordlists are ordered. You can see how they are being generated by browsing the SQL directory of the Commonspeak2 project, for example: https://github.com/assetnote/commonspeak2/blob/master/data/sql/http-archive/apiroutes.sql#L24

Usually, all wordlists are ordered by frequency (`ORDER BY count DESC`).
